//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int OwnerID { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Account Account { get; set; }
    }
}
